import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStore } from '@/store/useStore';
import { PredictionCard } from '@/components/PredictionCard';
import { PredictionDetailModal } from '@/components/PredictionDetailModal';
import { Button } from '@/components/ui/button';
import { CPU, ListFilter } from 'lucide-react';
import { Prediction } from '@/types';

type FilterType = 'All' | 'EPL' | 'La Liga' | 'Bundesliga' | 'Serie A' | 'Ligue 1' | 'Pending' | 'Resolved';

export default function DashboardPage() {
  const {
    upcomingPredictions, historicalPredictions,
    fetchPredictions, fetchStats, fetchAgentStatus,
  } = useStore();
  
  const [selectedPred, setSelectedPred] = useState<Prediction | null>(null);
  const [filter, setFilter] = useState<FilterType>('All');

  // Polling every 60s
  useEffect(() => {
    fetchPredictions();
    fetchStats();
    fetchAgentStatus();
    
    const interval = setInterval(() => {
      fetchPredictions();
      fetchStats();
      fetchAgentStatus();
    }, 60000);
    
    return () => clearInterval(interval);
  }, [fetchPredictions, fetchStats, fetchAgentStatus]);

  const allPredictions = [...upcomingPredictions, ...historicalPredictions].sort((a, b) => 
     new Date(b.match.kickoffTime).getTime() - new Date(a.match.kickoffTime).getTime()
  );

  const filteredPredictions = allPredictions.filter(p => {
    if (filter === 'All') return true;
    if (filter === 'Pending') return !p.result || p.result.status === 'pending';
    if (filter === 'Resolved') return p.result && p.result.status !== 'pending';
    // League exact match, assuming leagues from API are EPL, La Liga...
    if (filter === 'EPL' && p.match.league === 'Premier League') return true;
    return p.match.league === filter;
  });

  const filters: FilterType[] = ['All', 'EPL', 'La Liga', 'Bundesliga', 'Serie A', 'Ligue 1', 'Pending', 'Resolved'];

  return (
    <div className="container mx-auto px-4 py-8 md:py-12 min-h-screen">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col gap-6">
        
        <div className="flex flex-col md:flex-row justify-between items-center mb-4 gap-4">
           <div>
             <h1 className="text-3xl font-bold text-foreground">Predictions Feed</h1>
             <p className="text-muted-foreground mt-1">Live picks generated by our AI model</p>
           </div>
           
           <div className="flex items-center bg-white/5 border border-white/10 rounded-full p-1 overflow-x-auto max-w-full glass-card">
              <div className="pl-3 pr-2 text-muted-foreground"><ListFilter size={16} /></div>
              {filters.map(f => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={`px-3 py-1.5 text-xs font-medium rounded-full whitespace-nowrap transition-colors ${
                    filter === f ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground hover:bg-white/10'
                  }`}
                >
                  {f}
                </button>
              ))}
           </div>
        </div>

        {filteredPredictions.length === 0 ? (
           <div className="py-20 text-center glass-card rounded-2xl border-white/10 flex flex-col items-center justify-center">
             <div className="w-24 h-24 rounded-full bg-primary/10 flex items-center justify-center mb-6">
                <span className="text-4xl opacity-50">⚽</span>
             </div>
             <h3 className="text-2xl font-bold text-foreground mb-2">No value bets found today</h3>
             <p className="text-muted-foreground max-w-sm">Our model found no edge in the market that meets our confidence threshold. Check back later.</p>
           </div>
        ) : (
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
             <AnimatePresence>
               {filteredPredictions.map((pred) => (
                 <motion.div
                   key={pred.id}
                   layout
                   initial={{ opacity: 0, scale: 0.9 }}
                   animate={{ opacity: 1, scale: 1 }}
                   exit={{ opacity: 0, scale: 0.9 }}
                   transition={{ duration: 0.3 }}
                 >
                   <PredictionCard
                     prediction={pred}
                     onViewDetails={setSelectedPred}
                   />
                 </motion.div>
               ))}
             </AnimatePresence>
           </div>
        )}
      </motion.div>

      <PredictionDetailModal
        prediction={selectedPred}
        open={!!selectedPred}
        onClose={() => setSelectedPred(null)}
      />
    </div>
  );
}
