import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStore } from '@/store/useStore';
import { PredictionCard } from '@/components/PredictionCard';
import { PredictionDetailModal } from '@/components/PredictionDetailModal';
import { Button } from '@/components/ui/button';
import { ListFilter, Lock, Wallet } from 'lucide-react';
import { Prediction } from '@/types';
import { Skeleton } from '@/components/ui/skeleton';
import { ConnectButton, useActiveAccount } from 'thirdweb/react';
import { thirdwebClient, celoChain } from '@/config/thirdweb';


type FilterType = 'All' | 'EPL' | 'La Liga' | 'Bundesliga' | 'Serie A' | 'Ligue 1' | 'Pending' | 'Resolved';

function PredictionSkeleton() {
  return (
    <div className="glass-card p-5 rounded-xl border border-white/5 space-y-4 h-[280px]">
      <div className="flex justify-between items-center">
        <Skeleton className="h-4 w-16 bg-white/10" />
        <Skeleton className="h-6 w-24 bg-white/10 rounded-full" />
      </div>
      <div className="flex justify-between items-center my-6">
        <div className="flex -space-x-3">
          <Skeleton className="w-12 h-12 rounded-full bg-white/10" />
          <Skeleton className="w-12 h-12 rounded-full bg-white/10" />
        </div>
        <div className="space-y-2">
           <Skeleton className="h-4 w-20 bg-white/10" />
           <Skeleton className="h-4 w-20 bg-white/10" />
        </div>
      </div>
      <Skeleton className="h-8 w-full bg-white/10 mt-8" />
    </div>
  );
}

export default function DashboardPage() {
  const {
    upcomingPredictions, historicalPredictions, isLoading,
    fetchPredictions, fetchStats, fetchAgentStatus, stats
  } = useStore();
  
  const [selectedPred, setSelectedPred] = useState<Prediction | null>(null);
  const [filter, setFilter] = useState<FilterType>('All');
  const account = useActiveAccount();

  useEffect(() => {
    fetchPredictions();
    fetchStats();
    fetchAgentStatus();
    
    const interval = setInterval(() => {
      fetchPredictions();
      fetchStats();
      fetchAgentStatus();
    }, 60000);
    
    return () => clearInterval(interval);
  }, [fetchPredictions, fetchStats, fetchAgentStatus]);

  const allPredictions = [...upcomingPredictions, ...historicalPredictions].sort((a, b) => 
     new Date(b.match.kickoffTime).getTime() - new Date(a.match.kickoffTime).getTime()
  );

  const filteredPredictions = allPredictions.filter(p => {
    if (filter === 'All') return true;
    if (filter === 'Pending') return !p.result || p.result.status === 'pending';
    if (filter === 'Resolved') return p.result && p.result.status !== 'pending';
    if (filter === 'EPL' && p.match.league === 'Premier League') return true;
    return p.match.league === filter;
  });

  const filters: FilterType[] = ['All', 'EPL', 'La Liga', 'Bundesliga', 'Serie A', 'Ligue 1', 'Pending', 'Resolved'];

  if (!account?.address) {
    return (
      <div className="container mx-auto px-4 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-md mx-auto text-center"
        >
          <div className="flex flex-col md:flex-row justify-between items-center mb-4 gap-4">
            <div>
              <h1 className="text-3xl font-bold text-foreground">Predictions Feed</h1>
              <p className="text-muted-foreground mt-1">Live picks generated by our AI model</p>
            </div>
          </div>
          <h3 className="text-2xl font-bold text-foreground mb-3 text-balance">
            Connect Wallet to View
          </h3>
          <p className="text-muted-foreground max-w-sm mx-auto leading-relaxed mb-6">
            Live AI predictions and value bets are exclusively available to BetOracle users.
          </p>
          <div className="flex justify-center">
            <ConnectButton 
              client={thirdwebClient} 
              chain={celoChain}
              connectButton={{
                className: "gradient-primary text-black font-bold h-12 px-8 shadow-lg shadow-primary/20",
                label: "Connect Wallet"
              }}
            />
          </div>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 md:py-12 min-h-screen">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col gap-6">
        
        <div className="flex flex-col md:flex-row justify-between items-center mb-4 gap-4">
           <div>
             <h1 className="text-3xl font-bold text-foreground">Predictions Feed</h1>
             <p className="text-muted-foreground mt-1">Live picks generated by our AI model</p>
           </div>
           
           <div className="flex items-center bg-white/5 border border-white/10 rounded-full p-1 overflow-x-auto max-w-full glass-card">
              <div className="pl-3 pr-2 text-muted-foreground"><ListFilter size={16} /></div>
              {filters.map(f => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={`px-3 py-1.5 text-xs font-medium rounded-full whitespace-nowrap transition-colors ${
                    filter === f ? 'bg-primary text-primary-foreground font-bold shadow-[0_0_10px_rgba(53,208,127,0.3)]' : 'text-muted-foreground hover:text-foreground hover:bg-white/10'
                  }`}
                >
                  {f}
                </button>
              ))}
           </div>
        </div>

        {isLoading ? (
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[1, 2, 3, 4, 5, 6].map(i => <PredictionSkeleton key={i} />)}
           </div>
        ) : filteredPredictions.length === 0 ? (
           <div className="py-24 text-center glass-card rounded-2xl border-white/10 flex flex-col items-center justify-center relative overflow-hidden">
             
             {/* Abstract football viz in background */}
             <div className="absolute inset-0 pointer-events-none opacity-5 flex items-center justify-center">
               <div className="w-[300px] h-[300px] border border-white rounded-full"></div>
               <div className="absolute w-[1px] h-full bg-white"></div>
               <div className="absolute h-[1px] w-full bg-white"></div>
             </div>

             <div className="w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center mb-6 border border-primary/20 shadow-[0_0_20px_rgba(53,208,127,0.2)]">
                <span className="text-3xl">🤖</span>
             </div>
             <h3 className="text-2xl font-bold text-foreground mb-3 text-balance">
                Our AI analyzed {Math.max(145, stats.totalPredictions * 4)} matches today
             </h3>
             <p className="text-muted-foreground max-w-md mx-auto leading-relaxed">
                But none of them met our strict +8% edge threshold for value in the current market odds. <br className="hidden md:block" /> Check back for the next global fixture window.
             </p>
           </div>
        ) : (
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
             <AnimatePresence>
               {filteredPredictions.map((pred) => (
                 <motion.div
                   key={pred.id}
                   layout
                   initial={{ opacity: 0, scale: 0.9 }}
                   animate={{ opacity: 1, scale: 1 }}
                   exit={{ opacity: 0, scale: 0.9 }}
                   transition={{ duration: 0.3 }}
                 >
                   <PredictionCard
                     prediction={pred}
                     onViewDetails={setSelectedPred}
                   />
                 </motion.div>
               ))}
             </AnimatePresence>
           </div>
        )}
      </motion.div>

      <PredictionDetailModal
        prediction={selectedPred}
        open={!!selectedPred}
        onClose={() => setSelectedPred(null)}
      />
    </div>
  );
}
